---
version: "3.9"

name: "plex-reshare"

services:
  plex_reshare:
    image: "peterbuga/plex-reshare:latest"
    container_name: "plex_reshare"
    hostname: "plex_reshare"
    restart: "unless-stopped"
    env_file:
      - .env
    ports:
      # - 8080:8080  # mapping to starlette, for debugging mostly
      - 8000:8000
    logging:
      options:
        max-size: "5m"
    # enable for development
    # volumes:
    #   - "./app:/app"
    #   - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro"
    #   - "./nginx.vh.default.conf:/etc/nginx/conf.d/default.conf:ro"
    #   - "./supervisord.conf:/etc/supervisord.conf"
